import type { Product, ProductPresentation } from "./commercialTypes";

type DemoProductInput = Omit<Product, "image" | "status"> & {
  presentations: Omit<ProductPresentation, "id" | "productId" | "active">[];
};

const DEMO_IMAGE_SOURCE = "https://example.com/lupulados-demo-placeholder";

const demoProductsInput: DemoProductInput[] = [
  {
    id: "demo-wine-malbec",
    slug: "demo-wine-malbec",
    name: "Vino Malbec demo",
    description: "Tinto joven para reuniones. Referencia demostrativa.",
    category: "wine",
    mainCategory: "alcohol",
    subcategory: "Vinos",
    tags: ["vino", "tinto", "malbec"],
    demo: true,
    demoNote: "Precio ilustrativo, sin stock real confirmado.",
    sortOrder: 210,
    presentations: [
      { presentationType: "750ml", label: "Botella 750ml", volumeLiters: 0.75, unitPrice: 7200, category: "pack", sortOrder: 10 },
      { presentationType: "caja6", label: "Caja x6", volumeLiters: 4.5, unitPrice: 41000, category: "pack", sortOrder: 20 },
    ],
  },
  {
    id: "demo-wine-white",
    slug: "demo-wine-white",
    name: "Vino blanco demo",
    description: "Blanco seco de referencia para mesas y eventos.",
    category: "wine",
    mainCategory: "alcohol",
    subcategory: "Vinos",
    tags: ["vino", "blanco"],
    demo: true,
    demoNote: "Precio ilustrativo, sin stock real confirmado.",
    sortOrder: 220,
    presentations: [
      { presentationType: "750ml", label: "Botella 750ml", volumeLiters: 0.75, unitPrice: 6800, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-fernet-classic",
    slug: "demo-fernet-classic",
    name: "Fernet clasico demo",
    description: "Aperitivo amargo de referencia para combinar con gaseosa.",
    category: "fernet",
    mainCategory: "alcohol",
    subcategory: "Fernet y amargos",
    tags: ["fernet", "amargo"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 230,
    presentations: [
      { presentationType: "750ml", label: "Botella 750ml", volumeLiters: 0.75, unitPrice: 9500, category: "pack", sortOrder: 10 },
      { presentationType: "1l", label: "Botella 1L", volumeLiters: 1, unitPrice: 11800, category: "pack", sortOrder: 20 },
    ],
  },
  {
    id: "demo-vermouth-red",
    slug: "demo-vermouth-red",
    name: "Vermut rosso demo",
    description: "Vermut rojo para aperitivo o tragos simples.",
    category: "aperitif",
    mainCategory: "alcohol",
    subcategory: "Aperitivos y vermuts",
    tags: ["vermut", "aperitivo"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 240,
    presentations: [
      { presentationType: "750ml", label: "Botella 750ml", volumeLiters: 0.75, unitPrice: 7600, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-whisky-blend",
    slug: "demo-whisky-blend",
    name: "Whisky blend demo",
    description: "Whisky blend generico para validar pedidos mixtos.",
    category: "whisky",
    mainCategory: "alcohol",
    subcategory: "Whiskies y bourbons",
    tags: ["whisky", "blend"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 250,
    presentations: [
      { presentationType: "750ml", label: "Botella 750ml", volumeLiters: 0.75, unitPrice: 18500, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-bourbon",
    slug: "demo-bourbon",
    name: "Bourbon demo",
    description: "Bourbon generico para pruebas de catalogo.",
    category: "whisky",
    mainCategory: "alcohol",
    subcategory: "Whiskies y bourbons",
    tags: ["bourbon", "whisky"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 260,
    presentations: [
      { presentationType: "750ml", label: "Botella 750ml", volumeLiters: 0.75, unitPrice: 24500, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-gin-dry",
    slug: "demo-gin-dry",
    name: "Gin dry demo",
    description: "Gin seco de referencia para combinar con tonica.",
    category: "gin",
    mainCategory: "alcohol",
    subcategory: "Gin y ginebra",
    tags: ["gin", "ginebra"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 270,
    presentations: [
      { presentationType: "750ml", label: "Botella 750ml", volumeLiters: 0.75, unitPrice: 13200, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-vodka",
    slug: "demo-vodka",
    name: "Vodka demo",
    description: "Vodka neutro generico para validar subcategorias.",
    category: "vodka",
    mainCategory: "alcohol",
    subcategory: "Vodka",
    tags: ["vodka"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 280,
    presentations: [
      { presentationType: "750ml", label: "Botella 750ml", volumeLiters: 0.75, unitPrice: 11200, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-rum",
    slug: "demo-rum",
    name: "Ron dorado demo",
    description: "Ron dorado generico para cocteleria simple.",
    category: "rum",
    mainCategory: "alcohol",
    subcategory: "Ron",
    tags: ["ron"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 290,
    presentations: [
      { presentationType: "750ml", label: "Botella 750ml", volumeLiters: 0.75, unitPrice: 12600, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-tequila",
    slug: "demo-tequila",
    name: "Tequila blanco demo",
    description: "Tequila blanco generico para pruebas de pedidos.",
    category: "tequila",
    mainCategory: "alcohol",
    subcategory: "Tequila",
    tags: ["tequila"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 300,
    presentations: [
      { presentationType: "750ml", label: "Botella 750ml", volumeLiters: 0.75, unitPrice: 16800, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-liqueur",
    slug: "demo-liqueur",
    name: "Licor crema demo",
    description: "Licor dulce generico para sobremesa.",
    category: "liqueur",
    mainCategory: "alcohol",
    subcategory: "Licores",
    tags: ["licor"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 310,
    presentations: [
      { presentationType: "750ml", label: "Botella 750ml", volumeLiters: 0.75, unitPrice: 9800, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-cola",
    slug: "demo-cola",
    name: "Gaseosa cola demo",
    description: "Gaseosa cola para mezclar o acompanar.",
    category: "soft-drink",
    mainCategory: "non-alcohol",
    subcategory: "Gaseosas",
    tags: ["gaseosa", "cola"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 410,
    presentations: [
      { presentationType: "2-25l", label: "Botella 2.25L", volumeLiters: 2.25, unitPrice: 3200, category: "pack", sortOrder: 10 },
      { presentationType: "pack6", label: "Pack x6", volumeLiters: 13.5, unitPrice: 18000, category: "pack", sortOrder: 20 },
    ],
  },
  {
    id: "demo-tonic",
    slug: "demo-tonic",
    name: "Tonica demo",
    description: "Tonica para gin tonic y cocteleria.",
    category: "mixer",
    mainCategory: "non-alcohol",
    subcategory: "Tonicas",
    tags: ["tonica", "mixer"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 420,
    presentations: [
      { presentationType: "lata354", label: "Lata 354ml", volumeLiters: 0.354, unitPrice: 1400, category: "pack", sortOrder: 10 },
      { presentationType: "pack6", label: "Pack x6 latas", volumeLiters: 2.124, unitPrice: 7600, category: "pack", sortOrder: 20 },
    ],
  },
  {
    id: "demo-water",
    slug: "demo-water",
    name: "Agua mineral demo",
    description: "Agua mineral sin gas para eventos.",
    category: "water",
    mainCategory: "non-alcohol",
    subcategory: "Agua",
    tags: ["agua"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 430,
    presentations: [
      { presentationType: "1-5l", label: "Botella 1.5L", volumeLiters: 1.5, unitPrice: 1600, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-soda",
    slug: "demo-soda",
    name: "Soda demo",
    description: "Soda para tragos y mesas.",
    category: "water",
    mainCategory: "non-alcohol",
    subcategory: "Soda",
    tags: ["soda"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 440,
    presentations: [
      { presentationType: "2l", label: "Botella 2L", volumeLiters: 2, unitPrice: 1700, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-orange-juice",
    slug: "demo-orange-juice",
    name: "Jugo naranja demo",
    description: "Jugo listo para tragos o consumo sin alcohol.",
    category: "soft-drink",
    mainCategory: "non-alcohol",
    subcategory: "Jugos",
    tags: ["jugo", "naranja"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 450,
    presentations: [
      { presentationType: "1l", label: "Botella 1L", volumeLiters: 1, unitPrice: 2100, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-energy",
    slug: "demo-energy",
    name: "Energizante demo",
    description: "Bebida energizante de referencia para catalogo.",
    category: "soft-drink",
    mainCategory: "non-alcohol",
    subcategory: "Energizantes",
    tags: ["energizante"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 460,
    presentations: [
      { presentationType: "lata473", label: "Lata 473ml", volumeLiters: 0.473, unitPrice: 2300, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-ice",
    slug: "demo-ice",
    name: "Hielo demo",
    description: "Bolsa de hielo para conservadoras y tragos.",
    category: "ice",
    mainCategory: "non-alcohol",
    subcategory: "Hielo",
    tags: ["hielo"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 470,
    presentations: [
      { presentationType: "bolsa", label: "Bolsa", volumeLiters: 1, unitPrice: 3000, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-rental-chopera",
    slug: "demo-rental-chopera",
    name: "Alquiler de chopera demo",
    description: "Representacion visual del alquiler para eventos.",
    category: "accessory",
    mainCategory: "accessory",
    subcategory: "Alquileres",
    tags: ["chopera", "alquiler"],
    demo: true,
    demoNote: "El alquiler real se coordina por WhatsApp.",
    sortOrder: 510,
    presentations: [
      { presentationType: "evento", label: "Por evento", volumeLiters: 1, unitPrice: 15000, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-cups",
    slug: "demo-cups",
    name: "Vasos descartables demo",
    description: "Vasos para reuniones y eventos.",
    category: "accessory",
    mainCategory: "accessory",
    subcategory: "Vasos",
    tags: ["vasos"],
    demo: true,
    demoNote: "Producto demostrativo.",
    sortOrder: 520,
    presentations: [
      { presentationType: "pack50", label: "Pack x50", volumeLiters: 1, unitPrice: 6000, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-cooler",
    slug: "demo-cooler",
    name: "Conservadora demo",
    description: "Accesorio de evento sujeto a disponibilidad real.",
    category: "accessory",
    mainCategory: "accessory",
    subcategory: "Hieleras y conservadoras",
    tags: ["conservadora", "hielera"],
    demo: true,
    demoNote: "Disponibilidad a confirmar.",
    sortOrder: 530,
    presentations: [
      { presentationType: "evento", label: "Por evento", volumeLiters: 1, unitPrice: 9000, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-combo-fernet",
    slug: "demo-combo-fernet",
    name: "Combo Fernet demo",
    description: "Fernet, gaseosas cola y hielo en una linea cerrada.",
    category: "pack",
    mainCategory: "combo",
    subcategory: "Combos y ofertas",
    tags: ["combo", "fernet", "gaseosa", "hielo"],
    demo: true,
    demoNote: "Combo cerrado; no descuenta stock por componente.",
    components: ["Fernet demo", "Gaseosa cola demo", "Hielo demo"],
    sortOrder: 610,
    presentations: [
      { presentationType: "combo", label: "Combo cerrado", volumeLiters: 1, unitPrice: 18500, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-combo-gin",
    slug: "demo-combo-gin",
    name: "Combo Gin Tonic demo",
    description: "Gin, tonicas y hielo para validar pedidos de tragos.",
    category: "pack",
    mainCategory: "combo",
    subcategory: "Combos y ofertas",
    tags: ["combo", "gin", "tonica", "hielo"],
    demo: true,
    demoNote: "Combo cerrado; no descuenta stock por componente.",
    components: ["Gin dry demo", "Tonicas demo", "Hielo demo"],
    sortOrder: 620,
    presentations: [
      { presentationType: "combo", label: "Combo cerrado", volumeLiters: 1, unitPrice: 22000, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-combo-beer-event",
    slug: "demo-combo-beer-event",
    name: "Combo barril + chopera demo",
    description: "Referencia para probar un pedido de evento cervecero.",
    category: "pack",
    mainCategory: "combo",
    subcategory: "Combos y ofertas",
    tags: ["combo", "barril", "chopera", "vasos"],
    demo: true,
    demoNote: "No representa reserva ni disponibilidad real.",
    components: ["Barril Blonde Ale", "Chopera", "Vasos"],
    sortOrder: 630,
    presentations: [
      { presentationType: "combo", label: "Combo evento", volumeLiters: 20, unitPrice: 56000, category: "pack", sortOrder: 10 },
    ],
  },
  {
    id: "demo-combo-meeting",
    slug: "demo-combo-meeting",
    name: "Pack reunion demo",
    description: "Bebidas variadas para validar un carrito mixto.",
    category: "pack",
    mainCategory: "combo",
    subcategory: "Combos y ofertas",
    tags: ["combo", "reunion"],
    demo: true,
    demoNote: "Combo cerrado; precio ilustrativo.",
    components: ["Vino demo", "Agua demo", "Gaseosa demo", "Hielo demo"],
    sortOrder: 640,
    presentations: [
      { presentationType: "combo", label: "Pack reunion", volumeLiters: 1, unitPrice: 28500, category: "pack", sortOrder: 10 },
    ],
  },
];

export const demoStoreProducts: Product[] = demoProductsInput.map(({ presentations: _presentations, ...product }) => ({
  ...product,
  image: DEMO_IMAGE_SOURCE,
  status: "active",
}));

export const demoStorePresentations: ProductPresentation[] = demoProductsInput.flatMap((product) =>
  product.presentations.map((presentation) => ({
    ...presentation,
    id: `${product.id}:${presentation.presentationType}`,
    productId: product.id,
    active: true,
  })),
);
